services:
  listener:
    build:
      context: .
      dockerfile: listener_dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    command: ["build/bin/listener", "configs/listener/config.json"]
    volumes:
      - ./common:/app/common
      - ./configs/listener:/app/configs/listener
      - ./listener:/app/listener
      - ./Makefile:/app/Makefile
      - ./lib:/app/lib
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./cmake:/app/cmake
      - ./entrypoint.sh:/app/entrypoint.sh
    stop_signal: SIGTERM
    stop_grace_period: 9s
    tty: true
  poster:
    build:
      context: .
      dockerfile: poster_dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    command: ["build/bin/poster"]
    volumes:
      - ./common:/app/common
      - ./configs/poster:/app/configs/poster
      - ./poster:/app/poster
      - ./Makefile:/app/Makefile
      - ./lib:/app/lib
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./cmake:/app/cmake
      - ./entrypoint.sh:/app/entrypoint.sh
    stop_signal: SIGTERM
    stop_grace_period: 9s
    tty: true